export {default as Profile} from './Profile/Profile'
export {default as Header} from './Header/Header'
export {default as PostCreator} from './PostCreator/PostCreator'
export {default as Spinner} from './Spinner/Spinner'
export {default as Posts} from './Posts/Posts'
